version: '3'

services:
  config:
    image: burnswme/config
    deploy:
      replicas: 1
    ports:
      - 9000:9000
    networks:
      - automagic
                                                
networks:
  automagic:
    


   