CREATE TABLE STORY(
ST_ID INT,
ST_TITLE VARCHAR2(500),
ST_SWIMLANE INT,
ST_DESC VARCHAR2(4000),
ST_POINTS INT,
ST_COMPLETED TIMESTAMP,
ST_POSITION INT,
PRIMARY KEY(ST_ID)
);

CREATE TABLE BOARD(
BD_ID INT,
BD_NAME VARCHAR2(500),
BD_STARTDATE TIMESTAMP,
BD_DURATION INT,
PRIMARY KEY(BD_ID)
);

CREATE TABLE USER_BOARD_ROLE(
UBR_ID INT,
BD_ID INT,
USER_ID INT,
ROLE_ID INT,
PRIMARY KEY(UBR_ID)
);
/
CREATE SEQUENCE STORY_SEQ
  START WITH 1
  INCREMENT BY 1;
/

CREATE SEQUENCE BOARD_SEQ
  START WITH 1
  INCREMENT BY 1;
/
CREATE SEQUENCE UBR_SEQ
  START WITH 1
  INCREMENT BY 1;
/
INSERT INTO BOARD (BD_ID,BD_NAME,BD_STARTDATE,BD_DURATION)VALUES(99,'test',CURRENT_TIMESTAMP,2);
INSERT INTO BOARD (BD_ID,BD_NAME,BD_STARTDATE,BD_DURATION)VALUES(100,'test2',CURRENT_TIMESTAMP,1);
INSERT INTO BOARD (BD_ID,BD_NAME,BD_STARTDATE,BD_DURATION)VALUES(101,'test3',CURRENT_TIMESTAMP,3); 
/
INSERT INTO STORY (ST_ID,ST_TITLE,ST_SWIMLANE,ST_DESC,ST_POINTS,ST_POSITION)VALUES(99,'test',1,'test story',4,3);
INSERT INTO STORY (ST_ID,ST_TITLE,ST_SWIMLANE,ST_DESC,ST_POINTS,ST_COMPLETED,ST_POSITION)VALUES(100,'test2',1,'test story',5,CURRENT_TIMESTAMP,2);
INSERT INTO STORY (ST_ID,ST_TITLE,ST_SWIMLANE,ST_DESC,ST_POINTS,ST_COMPLETED,ST_POSITION)VALUES(101,'test3',1,'test story',9,CURRENT_TIMESTAMP,1);
/
COMMIT;
/



