CREATE TABLE BOARD (
  BD_ID INTEGER,
  BD_NAME VARCHAR2(4000) NOT NULL,
  BD_STARTDATE TIMESTAMP NOT NULL,
  BD_DURATION INTEGER NOT NULL,
  PRIMARY KEY(BD_ID)
);

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;