CREATE TABLE HISTORY ( 
  HIST_ID INTEGER,
  HIST_ACTION VARCHAR2(4000),
  BU_ID INTEGER,
  BD_ID INTEGER,
  HIST_TIMESTAMP TIMESTAMP,
  PRIMARY KEY(HIST_ID)
);

CREATE SEQUENCE HISTORY_SEQ
START WITH 1
INCREMENT BY 1;
