CREATE TABLE ROLE_TYPE (
  RT_ID INTEGER,
  RT_NAME VARCHAR2(4000),
  PRIMARY KEY(RT_ID)
);

INSERT INTO ROLE_TYPE VALUES (1, "Admin");
INSERT INTO ROLE_TYPE VALUES (2, "Owner");
INSERT INTO ROLE_TYPE VALUES (3, "Collaborator");