CREATE TABLE STORY (
  ST_ID INTEGER,
  ST_TITLE VARCHAR2(500),
  ST_SWIMLANE INTEGER,
  ST_DESC VARCHAR2(4000),
  ST_POINTS INTEGER,
  ST_COMPLETED TIMESTAMP,
  ST_POSITION INTEGER,
  PRIMARY KEY(ST_ID)
)