CREATE TABLE TASK (
  TSK_ID INTEGER,
  ST_ID INTEGER NOT NULL,
  TSK_NAME VARCHAR2(4000) NOT NULL,
  TSK_COMPLETED NUMBER(1) DEFAULT 0,
  TSK_POSITION INTEGER,
  PRIMARY KEY(TSK_ID)
);

CREATE SEQUENCE TASK_SEQ
START WITH 1
INCREMENT BY 1;
